[build]
  publish = "public"
  command = "yarn osuny build"

[build.environment]
  HUGO_VERSION = "0.161.1"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/osuny"
  to = "https://www.osuny.org"

[[redirects]]
  from = "/actualites/netlify-database/"
  to = "/actualites/2026-04-28-netlify-database-is-now-available/"

